module.exports = {
  'ACR-HR': {
    testName: 'ACR-HR',
    scoringNumber: 1,
    presentation: {
      paired: false,
    },
    scoreType: 'DMOS',
    scoreMetric: 'number',
    scaleLabels: [
      ['Excellent', 5],
      ['Good', 4],
      ['Fair', 3],
      ['Poor', 2],
      ['Bad', 1],
    ],
    startingVideoLabels: ['Starting video'],
    ratingLabels: ['Please rate the video'],
    buttons: ['Continue'],
    experimentOrder: ['VIDEO_A', 'VOTE_A'],
  },
  ACR: {
    testName: 'ACR',
    scoringNumber: 1,
    presentation: {
      paired: false,
    },
    scoreType: 'MOS',
    scoreMetric: 'number',
    scaleLabels: [
      ['Excellent', 5],
      ['Good', 4],
      ['Fair', 3],
      ['Poor', 2],
      ['Bad', 1],
    ],
    startingVideoLabels: ['Starting video'],
    ratingLabels: ['Please rate the video'],
    buttons: ['Continue'],
    experimentOrder: ['VIDEO_A', 'VOTE_A'],
  },
  SAMVIQ: {
    testName: 'SAMVIQ',
    scoringNumber: 1,
    presentation: {
      paired: false,
    },
    scoreType: 'DMOS',
    scoreMetric: 'number',
    scaleLabels: [
      ['Excellent', 5],
      ['Good', 4],
      ['Fair', 3],
      ['Poor', 2],
      ['Bad', 1],
    ],
    startingVideoLabels: ['Starting video'],
    ratingLabels: ['Please rate the video'],
    buttons: ['Continue', 'Replay'],
    experimentOrder: ['VIDEO_A', 'VOTE_A'],
  },
  DSCQS: {
    testName: 'DSCQS',
    scoringNumber: 2,
    presentation: {
      paired: true,
      order: ['Original', 'Distorted'],
      shuffle: true,
    },
    scoreType: 'DMOS',
    scoreMetric: 'number',
    scaleLabels: [
      ['Excellent', 5],
      ['Good', 4],
      ['Fair', 3],
      ['Poor', 2],
      ['Bad', 1],
    ],
    buttons: ['Continue'],
    startingVideoLabels: [
      'Starting pair of videos',
      'Starting video A',
      'Starting video B',
    ],
    ratingLabels: ['Please rate video A', 'Please rate video B'],
    experimentOrder: [
      'VIDEO_A',
      'VIDEO_B',
      'VIDEO_A',
      'VOTE_A',
      'VIDEO_B',
      'VOTE_B',
    ],
  },
  DSIS: {
    testName: 'DSIS',
    scoringNumber: 1,
    presentation: {
      paired: true,
      order: ['Original', 'Distorted'],
      shuffle: false,
    },
    scoreType: 'MOS',
    scoreMetric: 'number',
    scoredVideo: 'Distorted',
    scaleLabels: [
      ['Imperceptible', 5],
      ['Perceptible, but not annoying', 4],
      ['Slightly annoying', 3],
      ['Annoying', 2],
      ['Very Annoying', 1],
    ],
    startingVideoLabels: [
      'Starting pair of videos',
      'Starting video A',
      'Starting video B',
    ],
    ratingLabels: ['Please rate video B'],
    buttons: ['Continue'],
    experimentOrder: ['VIDEO_A', 'VIDEO_B', 'VOTE_B'],
  },
};
